title: Seek Dev Notes
description: Internal development documentation
baseurl: ""
url: ""

collections:
  docs:
    output: true
    permalink: /docs/:name/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
